apiVersion: apps/v1
kind: Deployment
metadata:
  name: report-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: report-service
  template:
    metadata:
      labels:
        app: report-service
    spec:
      containers:
      - name: report-service
        image: viviags/report-service:latest
        ports:
        - containerPort: 8083
        env:
        - name: DB_HOST
          value: mysql
        - name: DB_PORT
          value: "3306"

---
apiVersion: v1
kind: Service
metadata:
  name: report-service
spec:
  selector:
    app: report-service
  ports:
    - protocol: TCP
      port: 8083
      targetPort: 8083
  type: NodePort